services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    hostname: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../config/traefik/traefik.yml:/traefik.yml:ro"
      - "../config/traefik/auth.yml:/authentic/auth.yml"
    networks:
      - default
      - kiosk-int
      - proxy
    labels:
      - "traefik.docker.network=proxy"
    links:
      - server

  kioskcontroller:
    build:
      context: ..
      dockerfile: ./deployments/controller/Dockerfile
    ports:
      - 8099:8099
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: ".env"
    networks:
      - kiosk-int
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kioskcontroller.entrypoints=web"
      - "traefik.http.services.kioskcontroller.loadbalancer.server.port=8099"
      - "traefik.http.middlewares.kioskcontrollerstrip.stripprefix.prefixes=${CONTROLLERROUTE}"
      # - "traefik.http.routers.kioskcontroller.middlewares=kioskcontrollerstrip,middlewares-authentik@file"
      - "traefik.http.routers.kioskcontroller.middlewares=kioskcontrollerstrip"
      - "traefik.docker.network=kiosk-int"
      # - "traefik.http.routers.kioskcontroller.rule=Host(`${CONTROLLERHOST}`) && PathPrefix(`${CONTROLLERROUTE}`) || PathPrefix(`${CLEANROUTE}`)"
    links:
      - server

#   firefox:
#     restart: unless-stopped
#     image: jlesage/firefox
#     environment:
#       - LANG=ru_RU.UTF-8
#       - KEEP_APP_RUNNING=1
#       - DARK_MODE=1
#       - FF_OPEN_URL=web.monitoringtransporta.ru
#       - FF_KIOSK=1
#     ports:
#       - "5800:5800"
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.firefox.entrypoints=web"
#       - "traefik.http.services.firefox.loadbalancer.server.port=5800"
#       - "traefik.docker.network=kiosk-int"
#       - "traefik.http.routers.firefox.rule=HeaderRegexp(`Cookie`, `.*monitorcookie=3490dv5uzx256ovgjosv32pwufz3zmg9r398u4ntt147asxvzu91jpbp6j8vzxw6.*`)"
#       - "traefik.http.middlewares.autodetect.contenttype=true"
#  #     - "traefik.http.services.firefox.loadbalancer.proxyProtocol.version=2"
#     volumes:
#       - "./conf:/config:rw"

include:
  - path: ./authentik/docker-compose.yml

networks:
  kiosk-int:
    name: kiosk-int
    internal: true
  proxy:
    driver: bridge
    # external: true

  # Заменил external: true на driver: bridge, чтобы сеть автоматически создавалась при docker compose up -d
  default:
    name: kiosk-net
    driver: bridge
