// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "10985c47-3e7a-43d0-b26a-509573c41f76");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1721468778);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1721468778);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1721468688);
user_pref("app.update.lastUpdateTime.region-update-timer", 1721468778);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1721468749);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1721468778);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1721468778);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{f3587cea-9cad-44f5-9344-02efa8115707}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1721468684);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 144);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d17a1eb4-83ca-46d1-a574-f5acdf6a6a99}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1721468686);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1721468688488");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1721490288488");
user_pref("browser.search.newSearchConfig.enabled", true);
user_pref("browser.search.region", "RU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20240606121648");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1721468748");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20240606121648");
user_pref("browser.startup.homepage_override.mstone", "126.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1721468749);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1721468694763");
user_pref("distribution.alpinelinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "126.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "RU");
user_pref("dom.push.userAgentID", "26e9e19c4e654998a2effbcfa6ab10c4");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1721468778);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240606121648");
user_pref("extensions.lastAppVersion", "126.0.1");
user_pref("extensions.lastPlatformVersion", "126.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"8244c787-cebd-4eca-9ab5-b7bef172837f\",\"pictureinpicture@mozilla.org\":\"242ca0f5-9ac3-4b03-a6a0-5eede3149e30\",\"screenshots@mozilla.org\":\"f4e4c460-7b08-4c34-8872-35e8e62c0695\",\"webcompat-reporter@mozilla.org\":\"f46be0a9-56b8-4f05-9a7a-a289fcc9e1bf\",\"webcompat@mozilla.org\":\"4fc9a3b6-3f02-48ed-8389-667c147c9088\",\"default-theme@mozilla.org\":\"a62b10b7-587a-4489-824b-7eda431a41fe\",\"addons-search-detection@mozilla.com\":\"d4dcbcc5-cfc3-4250-bf0d-5c35991bf9f6\",\"google@search.mozilla.org\":\"090fe8a6-e3b2-4c01-b596-85282f57f69c\",\"wikipedia@search.mozilla.org\":\"a148474a-596e-4208-a4e8-eceec56a7703\",\"bing@search.mozilla.org\":\"525d9996-e36c-4416-9910-9f113ac2586e\",\"ddg@search.mozilla.org\":\"7f427349-c1b2-4029-9e1f-c2539b76dfa4\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "53a58bfb4c8124ad4f7655b99bfdea290033a085e0796b19245b33b91c0948fdac9f0c3e817130b352493a65d9a7a0fc8a7c1eedc618cdaa2b4580734a11cd9c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1721468779);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: 2147500036, errorCode: 2, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1721468779);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1721468779);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1721468779);
user_pref("media.gmp-gmpopenh264.version", "2.3.2");
user_pref("media.gmp-manager.buildID", "20240606121648");
user_pref("media.gmp-manager.lastCheck", 1721468779);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("memory.phc.enabled", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2024-07-20T09:44:46.845Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4311941d-4ede-44f7-a3dd-c5efcf370d89");
user_pref("services.settings.blocklists.addons-bloomfilters.last_check", 1721468778);
user_pref("services.settings.blocklists.gfx.last_check", 1721468778);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1721468778);
user_pref("services.settings.main.devtools-compatibility-browsers.last_check", 1721468778);
user_pref("services.settings.main.message-groups.last_check", 1721468778);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1721468778);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1721468778);
user_pref("services.settings.main.search-config-icons.last_check", 1721468778);
user_pref("services.settings.main.search-config-v2.last_check", 1721468778);
user_pref("services.settings.main.search-telemetry-v2.last_check", 1721468778);
user_pref("services.settings.main.translations-models.last_check", 1721468778);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1721468778);
user_pref("toolkit.startup.last_success", 1721468747);
user_pref("toolkit.telemetry.cachedClientID", "6115eeab-9922-4a94-9170-e55e0b4ad144");
user_pref("toolkit.telemetry.previousBuildID", "20240606121648");
