# http:
#   middlewares:
# # https://github.com/goauthentik/authentik/issues/2366
#     middlewares-authentik:
#       forwardAuth:
#         address: "http://auth.domain.com/outpost.goauthentik.io/auth/traefik"
#         trustForwardHeader: true
#         authResponseHeaders:
#           - X-authentik-username
#           - X-authentik-groups
#           - X-authentik-email
#           - X-authentik-name
#           - X-authentik-uid
#           - X-authentik-jwt
#           - X-authentik-meta-jwks
#           - X-authentik-meta-outpost
#           - X-authentik-meta-provider
#           - X-authentik-meta-app
#           - X-authentik-meta-version
http:
    middlewares:
        authentik:
            forwardAuth:
                address: http://server:9000/outpost.goauthentik.io/auth/traefik
                trustForwardHeader: true
                authResponseHeaders:
                    - X-authentik-username
                    - X-authentik-groups
                    - X-authentik-email
                    - X-authentik-name
                    - X-authentik-uid
                    - X-authentik-jwt
                    - X-authentik-meta-jwks
                    - X-authentik-meta-outpost
                    - X-authentik-meta-provider
                    - X-authentik-meta-app
                    - X-authentik-meta-version
    routers:
        default-router:
            rule: "Host(`controller.domain.com`)"
            middlewares:
                - authentik
            priority: 10
            service: app
        default-router-auth:
            rule: "Host(`controller.domain.com`) && PathPrefix(`/outpost.goauthentik.io/`)"
            priority: 15
            service: authentik
    services:
        app:
            loadBalancer:
                servers:
                    - url: http://kioskcontroller:8099
        authentik:
            loadBalancer:
                servers:
                    - url: http://server:9000/outpost.goauthentik.io